### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by felipesanches** [julian1/ice40-spi-usb-controller#1]
Please add licensing info. I presume this code uses the same license as IceProg. But for legal safety of future users of this code, you should explicitly state the licensing terms.

**Comment by felipesanches** [comment]
the simplest thing you can do is to copy this file into your repo:
https://github.com/cliffordwolf/icestorm/blob/master/COPYING

**Comment by julian1** [comment]
Thanks @felipesanches . Fixed!.

**Comment by felipesanches** [comment]
Cheers!!! :-D
